#include <stdint.h>

#include "stm32f4xx.h"

#include "adc.h"

#include "controller.h"
#include "gpio.h"
#include "timer.h"

#define ADC_VREF  3.3f // ADC V_ref
#define ADC_STEPS 4096 // Number of distinct values that can be generated by a 12-bit ADC

const float adc_voltage_scale = ADC_VREF / (float)(ADC_STEPS - 1);

void ADC_IRQHandler(void)
{
        gpio_set_pin(GPIO_PORT_A, GPIO_PIN_4);

        /*
         * The varaiable adc_value refers to the voltage value that is fed to the PA1 (ADC pin).
         * This voltage is then compared to the reference voltage to make the error signal which
         * feeds the compensator. The compensator generates the duty cycle command which is then
         * multiplied by the (TIM2_ARR - 1) to make the new CCR1, because TIM2 CH1 is responsible to
         * generate the PWM signal feeding the switches AH and BL. Reading the Data Register (DR)
         * here clears the EOC flag.
         */
        float adc_value = ADC1->DR * adc_voltage_scale;

        float error = controller_reference - adc_value;

        /*
         * Update the controller_reference for the next period. The step has been chosen in a way
         * that controller_reference reaches CONTROLLER_REF_TARGET after CONTROLLER_REF_STEPS steps.
         * This is a soft-start mechanism that can alleviate inrush currents when the converter
         * starts operating.
         */
        if (!controller_ref_reached_target)
        {
                controller_step_ref(CONTROLLER_REF_TARGET,
                                    CONTROLLER_REF_TARGET / CONTROLLER_REF_STEPS);
        }

        float control_signal = controller_step(error);

        // Update TIM2 CCR1 so that duty cycle will take effect in the next switching period.
        TIM2->CCR1 = (uint32_t)(control_signal * (TIM2_ARR - 1));

        gpio_clear_pin(GPIO_PORT_A, GPIO_PIN_4);
}

void adc_init(void)
{
        // Enable clock access to the ADC module.
        RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;

        /*
         * Calculate the prescaler value for the ADCCLK (maximum value possible is 36 MHz). This
         * clock is generated from the APB2 clock divided by a programmable prescaler that allows
         * the ADC to work at fPCLK2/2, /4, /6 or /8. Since we have 100 MHz as APB2 clock, the
         * fastest ADCCLK possible is 25 MHz by setting the prescaler to 4. Then, we set the
         * sampling time to 3 ADC cycles (minimum value possible) for the fastest sampling time. At
         * the end, we set the ADC resolution to 12 bits for the maximum accuracy. The ADC
         * conversion time for the aforementioned configuration is T_conv = 3 + 12 = 15 ADCCLK
         * cycle. Since ADCCLK is 25 MHz and core clock is 100 MHz, each ADC conversion takes
         * 15 * (100 / 25) = 60 CPU clock cycles. This does not mean that CPU is involved in this
         * conversion process, because it is entirely done by the ADC hardware. But, ADC should
         * finish the conversion so that we can start the calculation of the next switching period
         * duty cycle.
         */

        // Set ADCCLK to 25 MHz by setting the prescaler to 4 (ADCPRE bitfield should be 01).
        ADC1_COMMON->CCR &= ~ADC_CCR_ADCPRE;
        ADC1_COMMON->CCR |= ADC_CCR_ADCPRE_0;

        // Set Sampling time to 56 ADCCLK cycles.
        ADC1->SMPR2 &= ~(ADC_SMPR2_SMP1_0 | ADC_SMPR2_SMP1_1 | ADC_SMPR2_SMP1_2);
        ADC1->SMPR2 |= ADC_SMPR2_SMP1_0; // 15 cycles
        // ADC1->SMPR2 |= ADC_SMPR2_SMP1_1; // 28 cycles
        // ADC1->SMPR2 |= (ADC_SMPR2_SMP1_0 | ADC_SMPR2_SMP1_1); // 56 cycles
        // ADC1->SMPR2 &= ~ADC_SMPR2_SMP1;

        // Set ADC resolution to 12 bit to increase the accuracy.
        ADC1->CR1 &= ~ADC_CR1_RES_Msk;

        // Set conversion sequence length to 1.
        ADC1->SQR1 &= ~ADC_SQR1_L_Msk;

        // Set conversion sequence start to channel 1.
        ADC1->SQR3 &= ~ADC_SQR3_SQ1_Msk;
        ADC1->SQR3 |= ADC_SQR3_SQ1_0;

        // Set mode to single conversion mode by clearing the CONT bit in ADC1_CR2.
        ADC1->CR2 &= ~ADC_CR2_CONT;

        // Enable EOC (end of conversion) interrupt.
        ADC1->CR1 |= ADC_CR1_EOCIE;

        // Set priority to 0 (highest priority).
        NVIC_SetPriority(ADC_IRQn, 0);

        // Enable ADC interrupt in NVIC.
        NVIC_EnableIRQ(ADC_IRQn);

        // Select TIM2 TRGO event as external trigger for regular conversion.
        ADC1->CR2 &= ~ADC_CR2_EXTSEL_Msk;
        ADC1->CR2 |= ADC_CR2_EXTSEL_1;
        ADC1->CR2 |= ADC_CR2_EXTSEL_2;

        // Enable trigger on the falling edge.
        ADC1->CR2 &= ~ADC_CR2_EXTEN_Msk;
        ADC1->CR2 |= ADC_CR2_EXTEN_1;

        // Enable ADC module.
        ADC1->CR2 |= ADC_CR2_ADON;
}